sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t nuesslerm/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nuesslerm/client-test yarn test --coverage --watchAll=false

after_sucess:
  - docker build -t nuesslerm/multi-client ./client
  - docker build -t nuesslerm/multi-nginx ./nginx
  - docker build -t nuesslerm/multi-server ./server
  - docker build -t nuesslerm/multi-worker ./worker
  # log in to the docker CLI with encrypted env variables that were set up on travis CI
  - echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_ID" --password-stdin
  # take those built images and push them to docker hub
  - docker push nuesslerm/multi-client
  - docker push nuesslerm/multi-nginx
  - docker push nuesslerm/multi-server
  - docker push nuesslerm/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-462170392819'
  bucket_path: 'multi-docker'
  on:
    branch: master
  access_key_id: '$AWS_ACCESS_KEY'
  secret_access_key: '$AWS_SECRET_KEY'
